### PR TITLE
changed address to La Commune

### PR DESCRIPTION
**Pull request by lolaolah**
yes that was the wrong address so i changed it!

### CODE REVIEW

**Comment by ziad-saab** [comment]
Can you please change the description as well? Changing the name but keeping the same description feels wrong...

Also, there are other occurrences of griffin in the content. Can you find them and change them as appropriate?

**Comment by lolaolah** [comment]
Hi I updated all the files this time on this branch!

**Comment by nyanofthemoon** [comment]
Almost there! Once the description in file "src/about/index.html" ("out of the La Commune a leading startup accelerator") has been changed to the actual description matching La Commune ("coworking space hosting new tech startups"), I will accept the pull request.

**Comment by ziad-saab** [comment]
@lolaolah can you please check this one and update it?

**Pull request closed without merging**
