### PR TITLE
New teacher1

### PR DESCRIPTION
**Pull request by sumorocker**
I have switched out Ziad Saab with Allan MacDonald as well as added a new profile picture within Full Time Web Development folder and About!

### CODE REVIEW

**Comment by ziad-saab** [comment]
@sumorocker can you please load the image from your own project? It's not good practice to link to external images. Alternatively you could use Gravatar, which is safe and permits external links.

**Comment by sumorocker** [comment]
Hey I pushed it up after manipulating the SCSS, its very red!

**Comment by sumorocker** [comment]
SCSS in Intro-section.scss

**Comment by ziad-saab** [comment]
@sumorocker are you sure it's for this project?

**Pull request closed without merging**
